sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-mono/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Mono/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-arabic/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-Arabic/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-condensed/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-Condensed/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-devanagari/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-Devanagari/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-hebrew/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-Hebrew/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-jp/fonts/complete/ttf/hinted" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-JP/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-kr/fonts/complete/ttf/hinted" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-KR/fonts/complete/ttf"
# sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-tc/fonts/complete/ttf/hinted" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-TC/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-thai-looped/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-Thai-Looped/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-thai/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-Thai/fonts/complete/ttf"
# sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans-variable/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans-Variable/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-sans/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Sans/fonts/complete/ttf"
sh Google-Fonts-Fixes/scripts/check_for_updates_per_file.sh "packages/plex-serif/fonts/complete/ttf" "Google-Fonts-Fixes/fonts/IBM-Plex-Serif/fonts/complete/ttf"
